// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvGM7O2dDZLLEtHChI4-ouhYfHrfUHqm4',
    appId: '1:1090747709692:web:b3a899de6494f743e0bf79',
    messagingSenderId: '1090747709692',
    projectId: 'my-expense-tracker-6fb37',
    authDomain: 'my-expense-tracker-6fb37.firebaseapp.com',
    databaseURL: 'https://my-expense-tracker-6fb37-default-rtdb.firebaseio.com',
    storageBucket: 'my-expense-tracker-6fb37.firebasestorage.app',
    measurementId: 'G-1ZVSC6Q7X0',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgt7ogZdtcCwkpFtI8WIoRh_wNz6roT-4',
    appId: '1:1090747709692:ios:d0900af53402d18be0bf79',
    messagingSenderId: '1090747709692',
    projectId: 'my-expense-tracker-6fb37',
    databaseURL: 'https://my-expense-tracker-6fb37-default-rtdb.firebaseio.com',
    storageBucket: 'my-expense-tracker-6fb37.firebasestorage.app',
    iosBundleId: 'com.example.luminaExpenseTracker',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgt7ogZdtcCwkpFtI8WIoRh_wNz6roT-4',
    appId: '1:1090747709692:ios:d0900af53402d18be0bf79',
    messagingSenderId: '1090747709692',
    projectId: 'my-expense-tracker-6fb37',
    databaseURL: 'https://my-expense-tracker-6fb37-default-rtdb.firebaseio.com',
    storageBucket: 'my-expense-tracker-6fb37.firebasestorage.app',
    iosBundleId: 'com.example.luminaExpenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvGM7O2dDZLLEtHChI4-ouhYfHrfUHqm4',
    appId: '1:1090747709692:web:6cc38452c6e6d77ee0bf79',
    messagingSenderId: '1090747709692',
    projectId: 'my-expense-tracker-6fb37',
    authDomain: 'my-expense-tracker-6fb37.firebaseapp.com',
    databaseURL: 'https://my-expense-tracker-6fb37-default-rtdb.firebaseio.com',
    storageBucket: 'my-expense-tracker-6fb37.firebasestorage.app',
    measurementId: 'G-ERJ6CN986C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd02415uGUX-M1cL7zROmbBY25I5MgmXc',
    appId: '1:1090747709692:android:339ed46795d6e3b9e0bf79',
    messagingSenderId: '1090747709692',
    projectId: 'my-expense-tracker-6fb37',
    databaseURL: 'https://my-expense-tracker-6fb37-default-rtdb.firebaseio.com',
    storageBucket: 'my-expense-tracker-6fb37.firebasestorage.app',
  );
}
